version: "3.9"

services:
  mariadb:
    #    restart: always
    image: mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mariadb/mysql:/var/lib/mysql

  php:
#    restart: always
    build:
      context: ./volumes/php
      dockerfile: Dockerfile
      args:
        - PHP_TAG
        - LAVAVEL_TAG
    container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mariadb
    volumes:
      - ./laravel:/var/www/html
      - ./volumes/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  inertia:
#    restart: always
    build:
      context: ./volumes/inertia
      dockerfile: Dockerfile
      args:
        - PHP_TAG_CLI
    container_name: "${PROJECT_NAME}_inertia"
    depends_on:
      - php
    volumes:
      - ./laravel:/var/www/html
      - ./volumes/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
#    restart: always
    build:
      context: ./volumes/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - "${PROJECT_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./laravel:/var/www/html
      - ./volumes/nginx/site.conf:/etc/nginx/conf.d/site.conf
